### ISSUE TITLE
Viewing stats shows no data (ie, team record as 0, no entries)

### ISSUE THREAD

**Issue by rwd1959** [jleonard2099/LHG_Football#12]
Here are my files.
[96stats.zip](https://github.com/jleonard2099/LHG_Football/files/10333535/96stats.zip)
[96.zip](https://github.com/jleonard2099/LHG_Football/files/10333538/96.zip)

**Comment by jleonard2099** [comment]
Thanks investigating now but confirmed same problem as you reported. Rest assured I had issues with this during development so I've seen it and can fix it.

**Comment by jleonard2099** [comment]
Based on other reports of this it has been pointed out that the stats do not actually get compiled (the users / teams don't scroll across the screen). As I remember it this is a simple conditional that was broken. It is not clear why this issue has returned.

**Comment by jleonard2099** [comment]
This was for the Leader stats specifically, but I'll be checking all stat screens. I have a fully generated season of stats and will compare outputs in original version and mine.

**Comment by jleonard2099** [comment]
Below is an example of what I am witnessing. This indicates the need to review the calculation of win/loss records during compile.

![Football-LeagueStats0](https://user-images.githubusercontent.com/100517658/212374631-20a9e5e0-0976-4f4b-9edf-d0df9db416dc.png)

**Comment by jleonard2099** [comment]
Example of league leaders being all blank as well
![Football-LeageLeadersBlank](https://user-images.githubusercontent.com/100517658/212375104-d6d89d59-b5f0-4365-ae33-43e05fe25015.png)

**Comment by jleonard2099** [comment]
Currently have stat leaders showing up now, there was a logic bug in determining when to compile stats at all. This will be included in the next release.

Now troubleshooting Win-Loss record info.

**Comment by jleonard2099** [comment]
After cleaning out all files and compiling from scratch, this issue has now been resolved and records report accurately. Next version will include the fix.

**Comment by rwd1959** [comment]
👍
